### ISSUE TITLE
How to get the accuracy of the overall test set and the accuray in Y/N, other and number

### ISSUE THREAD

**Issue by zpltys** [yuleiniu/cfvqa#10]
[logs.txt](https://github.com/yuleiniu/cfvqa/files/7543029/logs.txt)
I try to run the baseline as "python -m bootstrap.run -o cfvqa/options/vqacp2/smrl_baseline.yaml", and got the logs.txt.
However, I cannot get the overall accuracy as similar in your paper (about 38.46), and how to get the accuracy of different question types (Y/N, other and number) from this log?

Should I run more epoch or change some super parameter?

**Comment by yuleiniu** [comment]
According to [the description of result files](https://github.com/yuleiniu/cfvqa#train-a-model), you can check the json file `logs_val_oe.json` to get the results of baseline. For example, for Y/N questions, the key is `eval_epoch.perAnswerType.yes/no`.

**Comment by zpltys** [comment]
Thanks for your reply!
