### ISSUE TITLE
Question about evaluation strategy

### ISSUE THREAD

**Issue by jediyoda36** [yuleiniu/cfvqa#11]
Hi,
Recently I'm doing my own VQA work. In my case, the convergence speed in three categories (`Y/N`, `Num.`, `Other`) are not same. Hence, the best result for each category may reveal in three different epoch. I'm little confused on how to choose the best result for each category.

So, in your work, how do you choose the best result for each category? 
Choose the  highest result for each category from all epochs result? 
Or just choose one epoch which has highest `All` score and choose all results from this epoch only?

**Comment by yuleiniu** [comment]
We simply report the results for the last epoch, i.e., choose all results from this epoch only. We did not choose the best result for each category.

**Comment by jediyoda36** [comment]
I see, thanks for reply!
