### ISSUE TITLE
Maybe something wrong in cfvqasimple.py

### ISSUE THREAD

**Issue by Mike4Ellis** [yuleiniu/cfvqa#4]
Hello, thanks for sharing your code! 
I found a possible wrong in cfvqasimple.py
Isn't `out['logits_all'] = z_qkv # for optimization`  should be `out['logits_all'] = z_qk # for optimization` ?  Or I took it wrong?

**Comment by hannajiang** [comment]
Hello, I want to ask a question. Can you get the result in paper, I got very low result in all files of .yaml; And I didn't modify any parameter.

**Comment by yuleiniu** [comment]
> Hello, thanks for sharing your code!
> I found a possible wrong in cfvqasimple.py
> Isn't `out['logits_all'] = z_qkv # for optimization` should be `out['logits_all'] = z_qk # for optimization` ? Or I took it wrong?

Thank you for pointing it out! I removed `cfvqasimple.py` as it is unused and redundant. The `cfvqasimple` option has been implemented using the `cfvqa.py` file by setting `is_va=False`.

**Comment by yuleiniu** [comment]
> Hello, I want to ask a question. Can you get the result in paper, I got very low result in all files of .yaml; And I didn't modify any parameter.

Hi Han, would you like to share more details?

**Comment by hannajiang** [comment]
Thanks for your reply, I run vqa2/smrl_baseline.yaml get best eval accuracy_top1 is 53.97;  run vqacp2/smrl_cfvqa_sum.yaml get beset eval accuracy_cfvqa_top1 is 47.60; I didn't modify any parameters; Maybe I did something wrong?

**Comment by yuleiniu** [comment]
> Thanks for your reply, I run vqa2/smrl_baseline.yaml get best eval accuracy_top1 is 53.97; run vqacp2/smrl_cfvqa_sum.yaml get beset eval accuracy_cfvqa_top1 is 47.60; I didn't modify any parameters; Maybe I did something wrong?

Are the results reported from `logs.txt`? The results should be reported in the json files. For example, results for CF-VQA can be found in `_cfvqa_val_oe.json`.

**Comment by hannajiang** [comment]
Sorry to bother you again, I run the code, and only generated logs.json.tmp but didn't generate the _cfvqa_val_oe.json file.

**Comment by yuleiniu** [comment]
> Sorry to bother you again, I run the code, and only generated logs.json.tmp but didn't generate the _cfvqa_val_oe.json file.

Were there any errors or warnings in the logs? Also, since this repo is built on top of [RUBi](https://github.com/cdancette/rubi.bootstrap.pytorch), are you able to run their code?

**Comment by hannajiang** [comment]
Yes, there is a ModuleNotFoundError: No module named 'block.external', I have modified the error.Thanks a lot.
