### ISSUE TITLE
No such file or directory: 'data/vqa/coco/extract_rcnn/2018-04-27_bottom-up-attention_fixed_36/COCO_val2014_000000144334.jpg.pth'

### ISSUE THREAD

**Issue by wspspring** [yuleiniu/cfvqa#5]
No such file or directory: 'data/vqa/coco/extract_rcnn/2018-04-27_bottom-up attention_fixed_36/COCO_val2014_000000144334.jpg.pth'

**Comment by yuleiniu** [comment]
Could you please check the path to the data?

**Comment by dev-salmanahmed** [comment]
@wspspring Please check your data directory. 
If you didn't run this script `bash rubi/datasets/scripts/download_vqa2.sh` then you get an error.

The following script contains:
```
mkdir -p data/vqacd data/vqa

wget http://data.lip6.fr/cadene/block/vqa2.tar.gz
wget http://data.lip6.fr/cadene/block/coco.tar.gz

tar -xzvf vqa2.tar.gztar -xzvf coco.tar.gz

mkdir -p data/vqa/coco/extract_rcnncd data/vqa/coco/extract_rcnn
wget http://data.lip6.fr/cadene/block/coco/extract_rcnn/2018-04-27_bottom-up-attention_fixed_36.tar

tar -xvf 2018-04-27_bottom-up-attention_fixed_36.tar
```
I hope this will resolve your error.
